apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-config
  namespace: webgoat
data:
  health-check.sh: |
    #!/bin/bash
    kubectl get pods -n webgoat
    kubectl get svc -n webgoat
    kubectl describe quota -n webgoat