
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webgoat-network-policy
  namespace: webgoat
spec:
  podSelector:
    matchLabels:
      app: webgoat
  policyTypes:
    - Ingress
    - Egress
egress:
  - to: []   # Autorise tout le trafic sortant
ingress:
  - from: [] # Autorise tout le trafic entrant sur les ports spécifiés
      