
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webgoat-network-policy
  namespace: webgoat
spec:
  podSelector:
    matchLabels:
      app: webgoat
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: [] 
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 3000
  egress:
    - to: []   