# service.yml
apiVersion: v1
kind: Service
metadata:
  name: webgoat
  namespace: webgoat
spec:
  type: NodePort
  selector:
    app: webgoat
  ports:
  - name: http
    port: 8080
    nodePort: 30080 
  - name: metrics
    port: 9090
    nodePort: 30090