apiVersion: v1
kind: ServiceAccount
metadata:
  name: webgoat-sa
  namespace: webgoat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webgoat-role
  namespace: webgoat
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]