apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  namespace: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: webgoat/webgoat:latest
        imagePullPolicy: Always
        args: ["--spring.main.allow-circular-references=true"]
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        - name: JAVA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom"
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 30
