apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat-ingress
  namespace: webgoat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: webgoat.local
    http:
      paths:
      - path: /webgoat(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: webgoat
            port:
              number: 8080
      - path: /prometheus(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
      - path: /grafana(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
