apiVersion: v1
kind: ResourceQuota
metadata:
  name: webgoat-quota
  namespace: webgoat
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "5"
    services: "3"
    persistentvolumeclaims: "5"