#Add settings prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webgoat-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: webgoat
  namespaceSelector:
    matchNames:
      - webgoat
  endpoints:
  - port: http
    interval: 15s
    path: /actuator/prometheus
    