apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
  namespace: webgoat
spec:
  selector:
    app: webgoat
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort

