apiVersion: v1
kind: Pod
metadata:
  name: webgoat-pod
  namespace: webgoat
spec:
  containers:
    - name: webgoat-container
      image: webgoat:latest
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"
