apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
  namespace: monitoring
data:
  values.yaml: |
    namespaceOverride: "monitoring"
    
    prometheus:
      prometheusSpec:
        replicas: 1
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        retentionSize: "5GB"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
    
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        route:
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'discord'
          routes:
          - match:
              severity: critical
            receiver: 'discord'
        receivers:
        - name: 'discord'
          webhook_configs:
          - url: '${DISCORD_WEBHOOK_URL}'  # À remplacer par une variable d'environnement