- name: Verify Kubernetes Components
  hosts: azure-vm
  become: yes
  tasks:
    - name: Verify kubelet is installed
      command: kubelet --version
      register: kubelet_version
      failed_when: kubelet_version.rc != 0
      changed_when: false

    - name: Show kubelet version
      debug:
        msg: "Kubelet version: {{ kubelet_version.stdout }}"

    - name: Verify kubeadm is installed
      command: kubeadm version
      register: kubeadm_version
      failed_when: kubeadm_version.rc != 0
      changed_when: false

    - name: Show kubeadm version
      debug:
        msg: "Kubeadm version: {{ kubeadm_version.stdout }}"

    - name: Verify kubectl is installed
      command: kubectl version --client
      register: kubectl_version
      failed_when: kubectl_version.rc != 0
      changed_when: false

    - name: Show kubectl version
      debug:
        msg: "Kubectl version: {{ kubectl_version.stdout }}"
