---
- name: Configure Kubernetes and Deploy WebGoat
  hosts: azure-vm
  become: yes
  tasks:
    # Vérification Kubernetes
    - name: Verify Kubernetes cluster
      command: kubectl cluster-info
      register: cluster_info
      changed_when: false

    # Création des namespaces
    - name: Create namespaces
      command: "{{ item }}"
      loop:
        - kubectl create namespace webgoat || true
        - kubectl create namespace monitoring || true
      changed_when: false

    # Déploiement des ressources WebGoat
    - name: Deploy WebGoat resources
      command: kubectl apply -f manifests/{{ item }}
      loop:
        - resource-quota.yml
        - service-account.yml
        - network-policy.yml
        - deployment.yml
        - service.yml
      args:
        chdir: "{{ playbook_dir }}"

    # Configuration Monitoring
    - name: Add Helm repos
      command: "{{ item }}"
      loop:
        - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        - helm repo add grafana https://grafana.github.io/helm-charts
        - helm repo update
      changed_when: false

    # Installation Prometheus et Grafana
    - name: Install monitoring stack
      command: "{{ item }}"
      loop:
        - helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f ../kubernetes/prometheus-values.yaml
        - helm install grafana grafana/grafana -n monitoring -f ../kubernetes/grafana-values.yaml

    # Vérification des déploiements
    - name: Verify deployments
      command: "{{ item }}"
      loop:
        - kubectl get pods,svc -n webgoat
        - kubectl get pods,svc -n monitoring
      register: deployment_status
      changed_when: false

    - name: Show deployment status
      debug:
        var: deployment_status.results