name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Vérifiez la structure du projet
      - name: Debug repository structure
        run: |
          pwd
          ls -R

      # Étape 3 : Compilez le code Java
      - name: Compile Java code with Maven
        run: |
          mvn -f path/to/your/real/pom.xml clean compile

      # Étape 4 : Analyse SonarQube
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=WebGoat
            -Dsonar.java.binaries=target/classes
            -Dsonar.branch.name=main

      # Étape 5 : Vérifier le Quality Gate (optionnel)
      - name: Check Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
