name: Build

on:
  push:
    branches:
      - main
  pull_request:  # Ajout de l'analyse sur les PR
    branches:
      - main

jobs:
  build:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour une analyse complète par SonarQube

      - name: Run SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality Gate Check (Optional)
        if: success()  # Exécute uniquement si l'analyse réussit
        uses: sonarsource/sonarqube-quality-gate-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
