name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Configurer Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Étape 2 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 3 : Compiler le code Java
      - name: Compile Java code with Maven
        run: |
          mvn -f WebGoat-main/pom.xml clean compile

      # Étape 4 : Exécuter SonarQube
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=WebGoat
            -Dsonar.java.binaries=WebGoat-main/target/classes

      # Étape 5 : Vérifier le Quality Gate
      - name: Check Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
