name: Container Security Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Configurer Java et Maven
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Étape 3 : Compiler le projet Maven
      - name: Build Project with Maven
        run: mvn clean package
        working-directory: ./WebGoat-main

      # Étape 4 : Construire l'image Docker
      - name: Build Docker Image
        run: docker build -t webgoat:latest ./WebGoat-main

      # Étape 5 : Scanner l'image Docker avec Trivy
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: webgoat:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
