name: Build and Analyze Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer Java et Maven
      - name: Set up JDK 17 with Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'       # Vous pouvez utiliser une version compatible avec votre projet
          distribution: 'temurin'  # Options disponibles : 'temurin', 'zulu', 'adopt', etc.
          cache: 'maven'           # Active le cache Maven

      # Étape 3 : Compiler le projet Maven
      - name: Build with Maven
        run: mvn clean package

      # Étape 4 : Construire l'image Docker
      - name: Build Docker Image
        run: docker build -t webgoat:latest ./WebGoat-main

      # Étape 5 : Scanner l'image Docker avec Trivy
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: webgoat:latest
