name: Container Security Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-scan:
    name: Scan Docker Image for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Installer Java et Maven
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Étape 3 : Compiler le projet et générer le fichier jar
      - name: Build Project with Maven
        run: mvn clean package
        working-directory: ./WebGoat-main

      # Étape 4 : Configurer Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Étape 5 : Construire l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t webgoat:latest ./WebGoat-main

      # Étape 6 : Scanner l'image Docker avec Trivy
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: webgoat:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
