name: Build and Analyze with SonarQube and Trivy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug workspace
      - name: Debug workspace
        run: ls -R

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build with Maven
      - name: Build with Maven
        run: mvn -f ./WebGoat-main/pom.xml clean package

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t webgoat:latest ./WebGoat-main

      # Scan Docker Image with Trivy
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: webgoat:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
 
