name: Deploy
on:
  workflow_run:
    workflows: ["Docker Build and Push", "Code Analysis"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f WebGoat-main/kubernetes/ --validate=false
          
      - name: Setup Monitoring
        run: |
          kubectl create namespace monitoring
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm install prometheus prometheus-community/kube-prometheus-stack -f WebGoat-main/prometheus/prometheus-kube.yml