name: Deployment
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'AhmedGafsi09/LOG8100_Projet'
          path: 'LOG8100_Projet'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/aks-node-1_key.pem
          chmod 600 ~/.ssh/aks-node-1_key.pem

      - name: Install Python and Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --user ansible

      - name: Set up Kubernetes config with SSH key and username
        env:
          VM_PRIVATE_KEY: ${{ secrets.VM_PRIVATE_KEY }}
        run: |
          mkdir -p $HOME/.kube
          echo "Creating kubeconfig with SSH key and username..."
          echo "{" > $HOME/.kube/config
          echo "  \"apiVersion\": \"v1\"," >> $HOME/.kube/config
          echo "  \"clusters\": [{" >> $HOME/.kube/config
          echo "    \"cluster\": {" >> $HOME/.kube/config
          echo "      \"insecure-skip-tls-verify\": true," >> $HOME/.kube/config
          echo "      \"server\": \"https://20.63.16.243:6443\"" >> $HOME/.kube/config
          echo "    }," >> $HOME/.kube/config
          echo "    \"name\": \"kubernetes\"" >> $HOME/.kube/config
          echo "  }]," >> $HOME/.kube/config
          echo "  \"contexts\": [{" >> $HOME/.kube/config
          echo "    \"context\": {" >> $HOME/.kube/config
          echo "      \"cluster\": \"kubernetes\"," >> $HOME/.kube/config
          echo "      \"user\": \"azureuser\"" >> $HOME/.kube/config
          echo "    }," >> $HOME/.kube/config
          echo "    \"name\": \"azureuser@kubernetes\"" >> $HOME/.kube/config
          echo "  }]," >> $HOME/.kube/config
          echo "  \"current-context\": \"azureuser@kubernetes\"," >> $HOME/.kube/config
          echo "  \"kind\": \"Config\"," >> $HOME/.kube/config
          echo "  \"preferences\": {}," >> $HOME/.kube/config
          echo "  \"users\": [{" >> $HOME/.kube/config
          echo "    \"name\": \"azureuser\"," >> $HOME/.kube/config
          echo "    \"user\": {" >> $HOME/.kube/config
          echo "      \"auth-provider\": {" >> $HOME/.kube/config
          echo "        \"config\": {" >> $HOME/.kube/config
          echo "          \"client-key-data\": \"$(cat ~/.ssh/aks-node-1_key.pem | base64 | tr -d '\n')\"" >> $HOME/.kube/config
          echo "        }" >> $HOME/.kube/config
          echo "      }" >> $HOME/.kube/config
          echo "    }" >> $HOME/.kube/config
          echo "  }]" >> $HOME/.kube/config
          echo "}" >> $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify Kubernetes Config File
        run: |
          echo "Verifying kubeconfig file:"
          cat $HOME/.kube/config

      - name: Debug Kubernetes Connection
        run: |
          echo "Testing Kubernetes config..."
          kubectl config view --raw
          kubectl cluster-info
