name: Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'AhmedGafsi09/LOG8100_Projet'
          path: 'LOG8100_Projet'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          scp -i ~/.ssh/id_rsa azureuser@${{ secrets.VM_HOST }}:.kube/config ~/.kube/
          chmod 600 ~/.kube/config
          
          # Update config with external IP
          sed -i 's/10.0.0.4/${{ secrets.VM_HOST }}/' ~/.kube/config
          
          # Test connection
          kubectl cluster-info

      - name: Apply Network Policies
        run: |
          kubectl apply -f ./kubernetes/calico/calico-config.yaml
          sleep 30  # Wait for policies to be applied

      - name: Deploy Application
        run: |
          kubectl apply -f kubernetes/deployment/
          kubectl rollout status deployment/webgoat -n webgoat --timeout=300s

      - name: Verify Deployment
        run: |
          kubectl get pods -n webgoat
          kubectl get services -n webgoat
          kubectl get networkpolicies -n webgoat