name: Deploy WebGoat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        repository: 'AhmedGafsi09/LOG8100_Projet'
        path: 'LOG8100_Projet'

    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible kubectl

    - name: Start Minikube
      run: |
        minikube start --driver=docker
        minikube status
        kubectl get nodes

    - name: Set Minikube Context
      run: |
        minikube update-context
        kubectl cluster-info

    - name: Run Ansible Playbook
      run: |
        cd LOG8100_Projet/WebGoat-main/ansible
        ansible-playbook -i inventory.yml site.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false

    - name: Verify Deployment
      run: |
        kubectl get pods -n webgoat
        kubectl get services -n webgoat
        minikube service list

    - name: Debug Info
      if: always()
      run: |
        kubectl get all -A
        kubectl describe nodes
