name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Terraform (optional: if using for infrastructure)
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    # Set up kubectl
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.31.2'  # Ensure this matches your cluster version

    # Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yml
        kubectl apply -f kubernetes/service.yml

    # Optional: Security Tests (e.g., Trivy)
    - name: Run Security Tests
      uses: aquasecurity/trivy-action@v0.7.0
      with:
        scan-type: fs
        severity: HIGH,CRITICAL
