name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: 'AhmedGafsi09/LOG8100_Projet'
          path: 'LOG8100_Projet'

      - name: Debug Paths
        run: |
          echo "Debugging paths and verifying directory structure..."
          echo "Current working directory:"
          pwd
          echo "Root directory content:"
          ls -al
          echo "Contents of LOG8100_Projet:"
          ls -al LOG8100_Projet
          echo "Contents of WebGoat-main:"
          ls -al LOG8100_Projet/WebGoat-main
          echo "Contents of kubernetes:"
          ls -al LOG8100_Projet/WebGoat-main/kubernetes

      - name: Create WebGoat Namespace
        run: |
          echo "Creating namespace for WebGoat..."
          kubectl create namespace webgoat || true
      
      - name: Apply WebGoat Pod Configuration
        run: |
          echo "Applying WebGoat Pod configuration..."
          kubectl apply -f LOG8100_Projet/WebGoat-main/kubernetes/webgoat-pod.yaml

      - name: Verify WebGoat Pod
        run: |
          echo "Verifying WebGoat Pod status..."
          kubectl get pods -n webgoat
