name: Deploy WebGoat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Security Tests
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        severity: HIGH,CRITICAL
        ignore-unfixed: true

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Verify Kubernetes Connection
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Deploy Infrastructure
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    - name: Deploy Application
      run: |
        cd kubernetes
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml

    - name: Verify Deployment
      run: |
        kubectl get pods -n webgoat
        kubectl get services -n webgoat
