name: Deploy WebGoat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        repository: 'AhmedGafsi09/LOG8100_Projet'
        path: 'LOG8100_Projet'

    - name: Debug directory structure
      run: |
        pwd
        ls -la
        ls -la LOG8100_Projet

    - name: Verify ansible folder
      run: |
        ls -la LOG8100_Projet/WebGoat-main/ansible

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      run: |
        cd LOG8100_Projet/WebGoat-main/ansible
        ansible-playbook -i inventory.yml site.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false

    - name: Deploy Infrastructure
      run: |
        cd LOG8100_Projet/WebGoat-main/terraform
        terraform init
        terraform apply -auto-approve

    - name: Deploy Application
      run: |
        cd LOG8100_Projet/WebGoat-main/kubernetes
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml

    - name: Verify Deployment
      run: |
        kubectl get pods -n webgoat
        kubectl get services -n webgoat
        minikube service list

    - name: Debug Info
      if: always()
      run: |
        kubectl get all -A
        kubectl describe pods -n webgoat
