name: Deploy WebGoat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        repository: 'AhmedGafsi09/LOG8100_Projet'
        path: 'LOG8100_Projet'

    - name: Debug directory
      run: |
        pwd
        ls -la
        ls -la LOG8100_Projet

    - name: Run Security Tests
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        severity: HIGH,CRITICAL
        ignore-unfixed: true

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Set up Minikube
    - name: Setup minikube
      uses: medyagh/setup-minikube@master

    - name: Try kubectl
      run: |
        minikube status
        kubectl get nodes
        kubectl get pods -A

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # Install Ansible
    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    # Run Ansible Playbook
    - name: Run Ansible Playbook
      run: |
        cd LOG8100_Projet/ansible
        ansible-playbook -i inventory.yml site.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false

    # Deploy Infrastructure with Terraform
    - name: Deploy Infrastructure
      run: |
        cd LOG8100_Projet/WebGoat-main/terraform
        terraform init
        terraform apply -auto-approve

    # Deploy Application with Kubernetes
    - name: Deploy Application
      run: |
        cd LOG8100_Projet/WebGoat-main/kubernetes
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml

    # Verify Deployment
    - name: Verify Deployment
      run: |
        kubectl get pods -n webgoat
        kubectl get services -n webgoat
        minikube service list

    # Debug Information
    - name: Debug Info
      if: always()
      run: |
        kubectl get all -A
        kubectl describe pods -n webgoat
