name: Deployment
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'AhmedGafsi09/LOG8100_Projet'
          path: 'LOG8100_Projet'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/aks-node-1_key.pem
          chmod 600 ~/.ssh/aks-node-1_key.pem
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Set up SSH Proxy
        run: |
          echo "Setting up SSH proxy..."
          ssh -i ~/.ssh/aks-node-1_key.pem -f -N -L 6443:localhost:6443 azureuser@20.63.16.243
          echo "SSH proxy established."

      - name: Set up Kubernetes config
        run: |
          mkdir -p $HOME/.kube
          echo "{" > $HOME/.kube/config
          echo "  \"apiVersion\": \"v1\"," >> $HOME/.kube/config
          echo "  \"clusters\": [{" >> $HOME/.kube/config
          echo "    \"cluster\": {" >> $HOME/.kube/config
          echo "      \"insecure-skip-tls-verify\": true," >> $HOME/.kube/config
          echo "      \"server\": \"https://localhost:6443\"" >> $HOME/.kube/config
          echo "    }," >> $HOME/.kube/config
          echo "    \"name\": \"kubernetes\"" >> $HOME/.kube/config
          echo "  }]," >> $HOME/.kube/config
          echo "  \"contexts\": [{" >> $HOME/.kube/config
          echo "    \"context\": {" >> $HOME/.kube/config
          echo "      \"cluster\": \"kubernetes\"," >> $HOME/.kube/config
          echo "      \"user\": \"kubernetes-admin\"" >> $HOME/.kube/config
          echo "    }," >> $HOME/.kube/config
          echo "    \"name\": \"kubernetes-admin@kubernetes\"" >> $HOME/.kube/config
          echo "  }]," >> $HOME/.kube/config
          echo "  \"current-context\": \"kubernetes-admin@kubernetes\"," >> $HOME/.kube/config
          echo "  \"kind\": \"Config\"," >> $HOME/.kube/config
          echo "  \"preferences\": {}," >> $HOME/.kube/config
          echo "  \"users\": [{" >> $HOME/.kube/config
          echo "    \"name\": \"kubernetes-admin\"," >> $HOME/.kube/config
          echo "    \"user\": {" >> $HOME/.kube/config
          echo "      \"token\": \"PLACEHOLDER_FOR_TOKEN\"" >> $HOME/.kube/config
          echo "    }" >> $HOME/.kube/config
          echo "  }]" >> $HOME/.kube/config
          echo "}" >> $HOME/.kube/config

      - name: Verify Kubernetes Config File
        run: |
          echo "Verifying kubeconfig file:"
          cat $HOME/.kube/config

          echo "Checking file size:"
          ls -lh $HOME/.kube/config

      - name: Test Kubernetes Connection
        run: |
          echo "Testing Kubernetes config..."
          kubectl config view --raw
          kubectl cluster-info
