name: Docker Build and Push
on:
  push:
    paths:
      - 'WebGoat-main/**'
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build WebGoat
        run: |
          mvn -f WebGoat-main/pom.xml clean package
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./WebGoat-main
          push: true
          tags: webgoat:latest
          
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: webgoat:latest
          severity: 'CRITICAL,HIGH'