serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'webgoat'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: webgoat
            action: keep