name: Deploy WebGoat
on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-webgoat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" | base64 -d > ~/.ssh/aks-node-1_key.pem
          chmod 600 ~/.ssh/aks-node-1_key.pem
          ssh-keyscan -H 20.63.16.243 >> ~/.ssh/known_hosts

      - name: Fetch Kubeconfig
        run: |
          ssh -i ~/.ssh/aks-node-1_key.pem azureuser@20.63.16.243 'cat ~/.kube/config' > $HOME/kubeconfig
          chmod 600 $HOME/kubeconfig
        env:
          KUBECONFIG: $HOME/kubeconfig

      - name: Verify Cluster Connection
        run: |
          export KUBECONFIG=$HOME/kubeconfig
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy WebGoat
        run: |
          export KUBECONFIG=$HOME/kubeconfig
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -
          cat << EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: webgoat
            namespace: webgoat
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: webgoat
            template:
              metadata:
                labels:
                  app: webgoat
              spec:
                containers:
                - name: webgoat
                  image: webgoat/webgoat:latest
                  ports:
                  - containerPort: 8080
                  resources:
                    limits:
                      memory: "1Gi"
                      cpu: "500m"
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
          EOF

          cat << EOF | kubectl apply -f -
          apiVersion: v1
          kind: Service
          metadata:
            name: webgoat
            namespace: webgoat
          spec:
            type: NodePort
            selector:
              app: webgoat
            ports:
            - port: 8080
              targetPort: 8080
              nodePort: 30080
          EOF

      - name: Wait for Deployment
        run: |
          export KUBECONFIG=$HOME/kubeconfig
          kubectl rollout status deployment/webgoat -n webgoat --timeout=300s

      - name: Verify Deployment
        run: |
          export KUBECONFIG=$HOME/kubeconfig
          kubectl get deployments -n webgoat
          kubectl get pods -n webgoat -o wide
          kubectl get svc -n webgoat
          echo "WebGoat is accessible at: http://20.63.16.243:30080/WebGoat"
