name: Deploy WebGoat
on:
  workflow_call:
  workflow_dispatch:
jobs:
  deploy-webgoat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Kubernetes config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          # Ajout d'une vérification
          kubectl config view
          kubectl cluster-info

      - name: Deploy WebGoat
        run: |
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/webgoat.yaml -n webgoat
