name: Deploy WebGoat

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy WebGoat
        run: |
          kubectl apply -f kubernetes/calico-config.yaml
          kubectl apply -f kubernetes/webgoat-deployment.yaml
          kubectl rollout status deployment/webgoat -n webgoat --timeout=300s

      - name: Verify Security
        run: |
          kubectl exec -n webgoat -l app=webgoat -- id
          kubectl exec -n webgoat -l app=webgoat -- ls -l /
          kubectl get networkpolicies -n webgoat

      - name: Check Application
        run: |
          POD_NAME=$(kubectl get pods -n webgoat -l app=webgoat -o jsonpath='{.items[0].metadata.name}')
          kubectl logs -n webgoat $POD_NAME
          kubectl get services -n webgoat
