name: Deploy WebGoat
on:
  workflow_call:
  workflow_dispatch:
jobs:
  deploy-webgoat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Prepare KUBECONFIG
        run: |
          echo "Creating .kube directory"
          mkdir -p ~/.kube
          
          echo "Checking if KUBECONFIG_CONTENT secret exists"
          if [ -z "${{ secrets.KUBECONFIG_CONTENT }}" ]; then
            echo "Error: KUBECONFIG_CONTENT secret is not set"
            exit 1
          fi
          
          echo "Decoding and writing kubeconfig"
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
          
          echo "Verifying kubeconfig file"
          if [ ! -f ~/.kube/config ]; then
            echo "Error: Kubeconfig file was not created successfully"
            exit 1
          fi
          
          chmod 600 ~/.kube/config
          ls -l ~/.kube/config
        
        env:
          KUBECONFIG: ~/.kube/config
      
      - name: Debug KUBECONFIG Contents
        run: |
          echo "Kubeconfig file contents:"
          cat ~/.kube/config || echo "Failed to read kubeconfig"
      
      - name: Set KUBECONFIG Environment
        run: |
          export KUBECONFIG=~/.kube/config
          echo "KUBECONFIG path: $KUBECONFIG"
      
      - name: Verify Cluster Connection
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get nodes
