name: Deploy WebGoat
on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-webgoat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/aks-node-1_key.pem
          chmod 600 ~/.ssh/aks-node-1_key.pem
          ssh-keyscan -H 20.63.16.243 >> ~/.ssh/known_hosts

      - name: Get Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          scp -i ~/.ssh/aks-node-1_key.pem azureuser@20.63.16.243:.kube/config $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy WebGoat
        run: |
          # Create namespace
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -

          # Deploy WebGoat
          cat << EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: webgoat
            namespace: webgoat
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: webgoat
            template:
              metadata:
                labels:
                  app: webgoat
              spec:
                containers:
                - name: webgoat
                  image: webgoat/webgoat:latest
                  ports:
                  - containerPort: 8080
                  resources:
                    limits:
                      memory: "1Gi"
                      cpu: "500m"
                    requests:
                      memory: "512Mi"
                      cpu: "250m"
          EOF

          # Create Service
          cat << EOF | kubectl apply -f -
          apiVersion: v1
          kind: Service
          metadata:
            name: webgoat
            namespace: webgoat
          spec:
            type: NodePort
            selector:
              app: webgoat
            ports:
            - port: 8080
              targetPort: 8080
              nodePort: 30080
          EOF

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/webgoat -n webgoat --timeout=300s

      - name: Verify deployment
        run: |
          echo "Deployment Status:"
          kubectl get deployments -n webgoat
          
          echo "Pod Status:"
          kubectl get pods -n webgoat -o wide
          
          echo "Service Status:"
          kubectl get svc -n webgoat
          
          echo "WebGoat will be accessible at:"
          echo "http://20.63.16.243:30080/WebGoat"
