name: Deploy WebGoat

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-webgoat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH and Kubeconfig
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
          
          mkdir -p ~/.kube
          ssh -i ~/.ssh/id_rsa azureuser@${{ secrets.VM_HOST }} 'sudo cat /etc/kubernetes/admin.conf' > ~/.kube/config
          chmod 600 ~/.kube/config
          
          # Vérifier la connexion
          KUBECONFIG=~/.kube/config kubectl cluster-info

      - name: Wait for API Server
        run: |
          attempt=1
          max_attempts=30
          until kubectl cluster-info &>/dev/null || [ $attempt -eq $max_attempts ]; do
            echo "Waiting for API server to become available (attempt $attempt/$max_attempts)..."
            sleep 10
            attempt=$((attempt + 1))
          done

          if [ $attempt -eq $max_attempts ]; then
            echo "API server did not become available in time"
            exit 1
          fi

      - name: Create and Configure Namespace
        run: |
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f - --validate=false
          
          # Attendre que le namespace soit prêt
          kubectl wait --for=condition=Active namespace/webgoat --timeout=60s

      - name: Deploy WebGoat
        working-directory: kubernetes
        run: |
          # Appliquer les configurations sans validation stricte
          kubectl apply -f . -n webgoat --validate=false
          
          # Attendre que le déploiement soit prêt
          kubectl rollout status deployment/webgoat -n webgoat --timeout=300s

      - name: Verify Deployment
        run: |
          echo "Listing Pods:"
          kubectl get pods -n webgoat
          
          echo "Listing Services:"
          kubectl get services -n webgoat
          
          echo "Getting Pod Logs:"
          kubectl logs -n webgoat -l app=webgoat --tail=50