name: Deploy WebGoat
on:
  workflow_call:
  workflow_dispatch:
jobs:
  deploy-webgoat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Kubernetes config
        run: |
          mkdir -p ~/.kube
          cat > ~/.kube/config << EOF
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: ${{ secrets.KUBE_CA_DATA }}
              server: https://20.63.16.243:6443
            name: kubernetes
          contexts:
          - context:
              cluster: kubernetes
              user: kubernetes-admin
            name: kubernetes-admin@kubernetes
          current-context: kubernetes-admin@kubernetes
          kind: Config
          users:
          - name: kubernetes-admin
            user:
              client-certificate-data: ${{ secrets.KUBE_CERT_DATA }}
              client-key-data: ${{ secrets.KUBE_KEY_DATA }}
          EOF
          chmod 600 ~/.kube/config

      - name: Deploy WebGoat
        run: |
          kubectl create namespace webgoat --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/webgoat.yaml -n webgoat
